export interface Blade {
  profile: string;
  vers: string;
  gpulabel: string;
  nimby: string;
  mem: number;
  bladeid: string;
  osname: string;
  ncpu: number;
  as: number;
  osversion: string;
  disk: number;
  numcmd: number;
  owners: string[] | null;
  udi: number;
  addr: string;
  siu: number;
  hnm: string;
  t0: number;
  note: string;
  t: number;
  lp: number;
  ns: number;
  cpu: number;

  provides: string[] | null;
}

export interface Job {
  comment: string;
  maxslots: number;
  numblocked: number;
  pil: number;
  spoolcwd: string;
  numerror: number;
  editpolicy: string;
  elapsedsecs: number;
  owner: string;
  numdone: number;
  spoolhost: string;
  maxtid: number;
  spooladdr: string;
  jid: number;
  maxactive: number;
  service: string;
  title: string;
  priority: number;
  spooltime: string;
  numtasks: number;
  crews: string[];
  maxcid: number;
  metadata: string;
  numready: number;
  tags: string[];
  lastnoteid: number;
  stoptime: string;
  envkey: [];
  tier: string;
  etalevel: number;
  projects: string[];
  dirmap: null;
  serialsubtasks: false;
  afterjids: number[];
  numactive: number;
  aftertime: null;
  assignments: string;
  spoolfile: string;
  esttotalsecs: number;
  starttime: string;
  pausetime: null;
  minslots: number;
  deletetime: null;
}
